#!/bin/sh

: ${LCQBE:=./lakec-qbe}

if [ $# = 0 ] ; then
	set -- test/*.lk
fi

numfail=0
got=$(mktemp)
trap 'rm "$got"' EXIT

for test ; do
	name=${test%.lk}
	if [ -f "$name.qbe" ] ; then
		want=$name.qbe
		set -- $LCQBE "$test"
	elif [ -f "$name.pp" ] ; then
		want=$name.pp
		set -- $LCQBE -E -I test/ "$test"
	else
		echo "invalid test '$test'" >&2
		set -- false
	fi
	if "$@" >"$got" 2>&1; diff -u "$want" "$got"; then
		result="PASS"
	else
		result="FAIL"
		numfail=$((numfail + 1))
	fi
	echo "[$result] $test" >&2
done

if [ "$numfail" -gt 0 ] ; then
	printf "%d test(s) failed\n" "$numfail"
	exit 1
fi
